baseURL = "https://southside.chillers.online/"
languageCode = "en-us"
title = "Southside Chillers"
theme = "ghostwriter"

[menu]
  [[menu.main]]
    identifier = "Ancestral"
    name = "Ancestral"
    url = "https://ancestral.chillers.online"
    weight = 11

[params]
  description = " "
  copyright = " "
  shareFacebook = false
  shareTwitter = false
  shareGooglePlus = false
  shareLinkedIn = false
